[ latticeHeight,latticeWidth,basisVector1,basisVector2,...
    unitCellHeight,unitCellWidth,dipoleUnitCell,dipoleLengthUnitCell] = coulombGetCrystalParameters;

[ coulombPositionMatrix, dipoleChargeMatrix ] = coulombConstructPositionMatrix( ...
    latticeHeight,latticeWidth,basisVector1,basisVector2,unitCellHeight,...
    unitCellWidth,dipoleUnitCell,dipoleLengthUnitCell);

[ totalEnergy ] = coulombCalculateDipoleEnergy( latticeHeight,...
    latticeWidth,coulombPositionMatrix,dipoleChargeMatrix )